@startuml

autonumber

ChillMedia -> LogIn : new()

LogIn -> LogIn : LogIn()

alt login successful
    LogIn -> LogIn : signIn()
else login failed
    LogIn -> LogIn : signUp()
end

LogIn -> ChillMedia : getCurrentUser()

@enduml