@startuml

' *****************
' CLASS
' *****************

class Main {
    + static void main(String[] args)
}

class ChillMedia {
    - IUser currentUser
    - final TextIO textIO
    - final FileIO fileIO
    - final ChillMediaFlow chillMediaFlow

    - final ArrayList<IGenre> genres
    - final ArrayList<IMovie> movies
    - final ArrayList<ISerie> series
    - final ArrayList<IUser> users

    + ChillMedia()
    - void load()
    + void run()

    - void listMovies()
    - void listSeries()

    + accessors methods()
}

class ChillMediaFlow {
    - final ChillMedia chillMedia
    - final IUser currentUser

    + ChillMediaFlow(ChillMedia chillMedia)

    + void searchMovies(int number)
    - void searchMoviesByTitle()
    - void searchMoviesByGenre()
    - void searchMoviesByRating()
    - void searchMyMovies()
    - void searchMyWatchedMovies()
    - void searchMovies(ArrayList<IMovie> movies)

    + void searchSeries(int number)
    - void searchSeriesByTitle()
    - void searchSeriesByGenre()
    - void searchSeriesByRating()
    - void searchSeries(ArrayList<ISeries> seriesList)

    - int chooseSeries(ArrayList<ISeries> series, int page, int pageSize)
    - int chooseMovie(ArrayList<IMovie> movies, int page, int pageSize)
    - int chooseMedia(ArrayList<IMedia> media, int page, int pageSize)

    - void addMovieToMyMovies(IMovie movie)
    - void removeMovieFromMyMovies(IMovie movie)
    - void watchMovie(IMovie movie)
    - void watchSeries(ISeries series)

    - int selectMovieOptions()
    - int selectSeriesOptions()
}

class LogIn {
    - IUser currentUser
    - final TextIO textIO
    - final ArrayList<IUser> users

    + LogIn(ChillMedia cm)

    + void logIn()
    - void signUp()
    - void signIn()
    - void createUser(String name, String email, String password, int age)
    - boolean checkEmailInList(String email)
    - IUser getUser(String email, String password)

    + accessors methods()
}

class Query {
    ' STATIC CLASS, EVT. KUNNE MAN LAVE EN INSTANS AF DENNE
    ' OG BRUGE DEN I CHILLMEDIA OG DERFRA BRUGE QUERY
    + static ArrayList<ISeries> searchSeriesGenre(ArrayList<ISeries> series, SeriesGenre genre)
    + static ArrayList<ISeries> searchSeriesGenre(ArrayList<ISeries> series, String genre)
    + static ArrayList<IMovie> searchMovieGenre(ArrayList<IMovie> movies, MovieGenre genre)
    + static ArrayList<IMovie> searchMovieGenre(ArrayList<IMovie> movies, String genre)
    + static ArrayList<IMovie> searchGenre(ArrayList<IMedia> movies, IGenre genre)

    + static ArrayList<ISeries> searchSeriesTitle(ArrayList<ISeries> series, String title)
    + static ISeries searchSeriesTitleSingle(ArrayList<ISeries> series, String title)
    + static ArrayList<IMovie> searchMovieTitle(ArrayList<IMovie> movies, String title)
    + static IMovie searchMovieTitleSingle(ArrayList<IMovie> movies, String title)
    + static ArrayList<IMedia> searchTitle(ArrayList<IMedia> medias, String title)

    + static ArrayList<ISeries> searchSeriesRating(ArrayList<ISeries> series, float minimumRating)
    + static ArrayList<IMovie> searchMovieRating(ArrayList<IMovie> movies, float minimumRating)
    + static ArrayList<IMedia> searchRating(ArrayList<IMedia> media, float minimumRating)
}

class TextIO {
    - static final Scanner scanner

    + TextIO()

    + String getUserInput(String msg)
    + String getUserInput(String msg, String[] options)
    + String getUserInput(String msg, int startIndex, String[] options)
    + String getUserInputFromMedia(String msg, int page, int pageSize, ArrayList<IMedia> media)

    + void println(String msg)
    + void print(String msg)
}

class FileIO implements IDataIO {
    - ArrayList<IMovie> movies
    - final String userPath
    - final String moviePath
    - final String seriesPath

    + ArrayList<IUser> loadUsers()
    - ArrayList<IUser> loadUsersFromJson()

    + void save(ArrayList<IUser> users)
    - void saveAsJson(ArrayList<IUser> users)

    + ArrayList<IMovie> loadMovies()
    + ArrayList<ISeries> loadSeries()
}

class User implements IUser {
    - static int idCounter
    - final int id
    - final String name
    - final String email
    - final String password
    - final int age
    - final boolean isAdult
    - final ArrayList<IMovie> myMovies
    - final ArrayList<IMovie> watchedMovies

    + User(int ID, String name, String email, String password, int age, ArrayList<IMovie> myMovies, ArrayList<IMovie> watchedMovies)
    + boolean addMyMovie(IMovie movie)
    + boolean removeMyMovie(IMovie movie)
    + void addWatchedMovie(IMovie movie)

    + accessors methods()
}

class Movie extends AWatchable implements IMovie {
    - final int year

    + Movie(String title, float rating, ArrayList<IGenre> genres, int year)

    + accessors methods()
}

class Series extends AWatchable implements ISeries {
    - final int startYear
    - final int endYear
    - final ArrayList<Season> seasons

    + Series(String title, int startYear, int endYear, float rating, ArrayList<IGenre> genres, ArrayList<Season> seasons)

    + accessors methods()
}

class Season extends ASeason {
    - final int seasonNumber
    - final int episodeCount

    + Season(int seasonNumber, int episodeCount)

    + accessors methods()
}

' *****************
' ABSTRACT CLASS
' *****************

abstract class AWatchable implements IMedia {
    - final String title
    - final float rating
    - final ArrayList<IGenre> genres

    + AWatchable(String title, float rating, ArrayList<IGenre> genres)

    + accessors methods()
}

' *****************
' INTERFACES
' *****************

interface IMedia {
    + String getTitle()
    + float getRating()
    + ArrayList<IGenre> getGenres()
}

interface ISeries extends IMedia {
    + int getStartYear()
    + int getEndYear()
    + ArrayList<Season> getSeasons()
}

interface IMovie extends IMedia {
    + int getYear()
}

interface IUser {
    + int getID()
    + String getName()
    + String getEmail()
    + String getPassword()
    + int getAge()
    + boolean isAdult()
    + ArrayList<IMovie> getMyMovies()
    + ArrayList<IMovie> getWatchedMovies()
    + boolean addMyMovie(IMovie movie)
    + boolean removeMyMovie(IMovie movie)
    + void addWatchedMovie(IMovie movie)
}

interface IDataIO {
    + ArrayList<IUser> loadUsers()
    + ArrayList<IMovie> loadMovies()
    + ArrayList<ISeries> loadSeries()
}

interface IGenre { }

' *****************
' ENUMS
' *****************

enum MovieGenre implements IGenre {
    CRIME,
    DRAMA,
    BIOGRAPHY,
    SPORT,
    HISTORY,
    ROMANCE,
    WAR,
    MYSTERY,
    ADVENTURE,
    FAMILY,
    FANTASY,
    THRILLER,
    HORROR,
    FILM_NOIR,
    ACTION,
    SCI_FI,
    COMEDY,
    MUSICAL,
    WESTERN,
    MUSIC
}

enum SeriesGenre implements IGenre {
    TALK_SHOW,
    DOCUMENTARY,
    CRIME,
    DRAMA,
    ACTION,
    ADVENTURE,
    COMEDY,
    FANTASY,
    ANIMATION,
    HORROR,
    SCI_FI,
    WAR,
    THRILLER,
    MYSTERY,
    BIOGRAPHY,
    HISTORY,
    FAMILY,
    WESTERN,
    ROMANCE,
    SPORT
}

' *****************
' RELATIONS
' *****************

Main *-- ChillMedia

ChillMedia *-- IMedia
ChillMedia *-- TextIO
ChillMedia *-- IDataIO
ChillMedia *-- IUser
ChillMedia *-- LogIn
ChillMedia *-- ChillMediaFlow

Series *-- ASeason

@enduml